# GitHub Actions build workflow
name: build

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies - Windows
        run: |
          choco install wget
        if: matrix.os == 'windows-latest'

      - name: Build
        run: |
          pip install -U pip wheel coverage coveralls
          pip install .
          python -c "import nltk; nltk.download('punkt')"
          pip install https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.2.5/en_core_sci_md-0.2.5.tar.gz
          python --version
          make data coverage
        env:
          PYTHONUTF8: 1

      - name: Test Coverage
        run: coveralls
        if: matrix.os == 'ubuntu-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}